### ISSUE TITLE
Update value sets, single element and comments export

### ISSUE THREAD

**Issue by maxence-lefort** [haffonist/igamt#1438]
- [x] Update value sets export

- [ ] Add single element constraints

- [x] Update comments export
